### ISSUE TITLE
Skip Files

### ISSUE THREAD

**Issue by kyle-turn2** [RasmusBuchholdt/simply-web-deploy#5]
Could you please allow an array of file names and/or patterns that we could use to skip individual files? These scripts work great but I need to ignore the appsettings.json file in the root directory.

**Comment by rasmusbuchholdt** [comment]
Thanks for the suggestion! I’ll be adding two optional parameters soon:

- One for passing an array of specific files to skip
- Another for passing an array of regex patterns that will be used for skipping as well

I likely won’t have time to work on it before the weekend, but it’s on my list.

**Comment by rasmusbuchholdt** [comment]
I have made some progress on it and have tagged it as `2.2.0-preview`, would you mind help testing it? You can see the updated read me here: https://github.com/rasmusbuchholdt/simply-web-deploy/tree/5-skip-files

You should be able to run it on your pipeline with: `uses: rasmusbuchholdt/simply-web-deploy@2.2.0-preview`

**Comment by kyle-turn2** [comment]
Great! Thank you. Yes, I will test today and let you know the results.

**Comment by kyle-turn2** [comment]
This does not seem to work, it may not be reading the new inputs appropriately. Below is what I tried and my results.

```
    - name: Deploy to IIS
      uses: rasmusbuchholdt/simply-web-deploy@2.2.0-preview
      with:
        website-name: ${{ steps.set-env.outputs.WEBSITE_NAME }}
        server-computer-name: ${{ steps.set-env.outputs.SERVER_COMPUTER_NAME }}
        server-username: ${{ secrets.PUBLISH_SERVER_USERNAME }}
        server-password: ${{ secrets.PUBLISH_SERVER_PASSWORD }}
        source-path: '\publish\'
        target-delete: true
        skip-files: 'web.config,appsettings.json'
```

```
Run rasmusbuchholdt/simply-web-deploy@2.2.0-preview
  with:
    website-name: xxxxx.com
    server-computer-name: https://xxxxx.com:8172
    server-username: ***
    server-password: ***
    source-path: \publish\
    target-delete: true
    skip-files: web.config,appsettings.json
    target-path: ""
    skip-directory-paths: ""
    skip-patterns: ""
```

```
------------------------------------
Starting deployment with parameters:
Source:               \publish\
Destination:          
Recycle App:          xxxxx.com
Computer Name:        https://xxxxx.com:8172
Delete target:        
Skip Directory Paths: 
Skip Files:           
Skip Regex Patterns:  
------------------------------------
Info: Using ID 'xxxxx' for connections to the remote server.
Info: Deleting file (xxxxx.com\appsettings.json).
```
